databases:
  - name: meta
    databaseName: meta
    user: postgres

services:
  - type: web
    name: Trading
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Trading.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meta
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4